name: "Download Cantera Test Files"
description: "Download and cache Cantera's Python test suite"
inputs:
  incoming-sha:
    description: The hash of the commit that should be downloaded
    required: true
outputs:
  test-root:
    description: The root folder where the tests are located
    value: ${{ runner.temp }}

runs:
  using: "composite"
  steps:
  - name: Restore cached the test files
    uses: actions/cache/restore@v4
    id: restore-cache
    with:
      path: ${{ runner.temp }}/test
      # Bump the integer to bust the cache
      key: ${{ inputs.incoming-sha }}-0
  - name: Download and unpack the tarball
    if: steps.restore-cache.outputs.cache-hit != 'true'
    run: |
      curl -fsSL "https://github.com/cantera/cantera/archive/${{ inputs.incoming-sha }}.tar.gz" -o ${{ runner.temp }}/cantera.tar.gz
      tar -xzf ${{ runner.temp }}/cantera.tar.gz --strip-components=1 -C ${{ runner.temp }} "cantera-${{ inputs.incoming-sha }}/test"
      rm ${{ runner.temp }}/cantera.tar.gz
    shell: bash
  - name: Save the test file cache
    uses: actions/cache/save@v4
    if: always() && steps.restore-cache.outputs.cache-hit != true
    id: save-cache
    with:
      path: ${{ runner.temp }}/test
      key: ${{ steps.restore-cache.outputs.cache-primary-key }}
